base_url = "https://hernangonzalez.github.io/rustar-resources"
title = "RustAR Resources"
description = "Please find here the content used in presentations during our meet-ups."
theme = "terminimal"
default_language = "en"

[markdown]
highlight_code = true
render_emoji = true

[extra]
show_only_description = true
accent_color = "orange"
logo_text = "Rust Argentina - Resources"
#logo_home_link = "https:// " # Go to main site?
