# do NOT include a trailing slash on the base URL
base_url = "http://rust-lang-ar.github.io/"
# Usable site directly from disk, Including Search: "/home/jieiku/.dev/abridge/public"
# Also set index format = "elasticlunr_javascript", and in [extra] uglyurls = true, integrity = false
# If you use the npm/node script then all you have to do is set offline = true, and everything else is automatic.

title = "RustAR Resources"
description = "Please find here the content used in presentations during our meet-ups."
theme = "abridge"

default_language = "en"
compile_sass = true
minify_html = false
build_search_index = true
generate_feed = true


[search] # Options specific to elasticlunr search.
# index format can be: elasticlunr_json or elasticlunr_javascript
index_format = "elasticlunr_json"
include_title = true              # include title of page/section in index
include_description = true        # include description of page/section in index
include_content = true            # include rendered content of page/section in index
# truncate_content_length = 100 # Truncate at nth character. May be useful if index is getting too large.

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = false
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

# Any Extra language you do not use, delete or comment out the extra language sections:
[extra]
toc = true
recent = true     # TOC / index
recent_items = 15
series = true
series_items = 9  # Max number of items to display in series list, use 0 to disable
#Series_parts = "$NUMBER_OF_PARTS part Series"

meta_index = { position = "bottom", size = "s90", author = false, readtime = false, readstring = "min", date = true, updated = false, categories_tags = true, divider = "" }
meta_post = { position = "top", size = "s95", author = true, readtime = false, readstring = "min read", date = true, updated = true, categories_tags = true, divider = "" }

hide_section_dates = false        # hides the date for sections that use posts.html as their template.
hide_page_nextprev_titles = false # hides the next/previous titles for pages that use page.html as their template.
title_size_index = "s85"
footer_size = "s90"
footer_credit = true
#footer_credit_override = '<p class="s90">Powered by <a href="https://www.getzola.org/" target="_blank">Zola</a> &#38; <a href="https://github.com/Jieiku/abridge/" target="_blank">Abridge</a></p>'
#archive_reverse = true # Set to True to sort posts chronologically per year instead of newest first on the archive page: example.com/archive/

### Uncomment one of the below lines, or neither, depending on which type of logo you want to use:
#logo = { file="logo.svg", width="32", height="32", alt="Abridge", text="bridge" }
textlogo = '<font color="#f90">Rust</font> Argentina - Resources'
# textlogo = '<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#f90" viewBox="0 0 96 96" width="28" height="28"><path stroke-width="14" d="M14 99 46 7h4l32 92"/><path stroke-width="9" d="M-3 82c43-26 59-26 102 0"/><path stroke-linecap="round" stroke-width="1.5" d="M94 72v7m-5-9.8v7m-5-9.8v7.1M79 64v7M63 57.7v7m-5-8.2v7m-5-7.8v7m-5-7.2v7m-5-6.7v7m-5-6.3v7m-5-5.8v7M17 64v7m-5-4.6v7m-5-4.2v7M2 72v7"/></svg>bridge'

sitedesc = false # enables or disables the display of the site description below the logo.
headhr = false   # show or hide horizontal rule below header
foothr = true    # show or hide horizontal rule above footer

###############################################################################
### Resource Files
### You can load extra css files if you need to, just separate by comma:
### stylesheets = [ "abridge.css", "extra.css" ]
### search_library, library to use. valid values:
###   false, "elasticlunr", "tinysearch", "stork"
### offline: implies uglyurls=true and integrity=false, when true NPM/node will
###   automatically set the path for the base_url, it will build the site,
###   then set the base_url back to what it was. This is a way to build a completely
###   offline site, a feature not possible with Zola alone.
###   The PWA feature is another way to build an offline site, so there are now two
###   different ways to build an offline site with Abridge.
###
### For most people the value of online_url will be the same as base_url.
###   online_url is used to restore the base_url after generating an Offline site.
###   When you set offline = true and run the npm script, the base_url is set to the absolute path on disk.
###   Once you set offline = false, the base_url will be set back to the value of online_url when you run the npm script again.
###############################################################################

# do NOT include a trailing slash on the online URL
#online_url = "https://abridge.netlify.app"
online_indexformat = "elasticlunr_json" # used to restore your preferred index format when offline = false
offline = false                         # implies uglyurls=true and integrity=false, when true NPM/node will automatically set the path for the base_url, it will build the site, then set the base_url back to what it was.

uglyurls = false # if set to true then links are generated with the full path. eg https://abridge.netlify.app/index.html
integrity = true # increases site security, should normally be true. (setting to false is useful during js development)
js_bundle = true # multiple javascript files combined into a single file (setting to false is useful during js development)

js_copycode = true           # The copy button on code blocks that allows you to copy them to the clipboard.
js_email_encode = true       # obfuscates email address in footer
js_prestyle = true           # used to preload: FontAwesome, Katex, external Google Fonts
js_switcher = true           # The button that allows manually changing between light/dark mode.
js_switcher_default = "dark" # default nojs switcher mode: dark, light (make sure to also set $switcherDefault in abridge.scss)

search_library = 'elasticlunr'
stylesheets = ["abridge.css"]

webmanifest = "manifest.min.json" # Required for PWAs

###############################################################################
### PWA (Progressive Web Application)
### By default Abridge has pwa_NORM_TTL and pwa_LONG_TTL set to 0, this essential turns the PWA cache strategy into network first.
###  Abridge uses cachebust hashing on js and css files, so anytime a page cache is updated, these resources would also get updated if changed.
###  Media files rarely change, especially font files, so it is a good idea cache indefinitely.
###  For pwa_TTL_EXEMPT indefinitely cached resources, you can force a new cache by incrementing the pwa_VER (cache version number).
### If you would like to try a cache first strategy then set a value higher than 0 for pwa_NORM_TTL and pwa_LONG_TTL.
###  The options below other than pwa=true, only come into play when the npm/node script is ran.
###############################################################################

pwa = true         # true to load the service worker
pwa_VER = '3.11.0' # Service Worker cache version. (increment if you need to force a new cache)

### 3600=1hour, 28800=8hours, 86400=1day, 604800=1week, 1209600=2weeks
pwa_NORM_TTL = 0 #  86400 is reasonable. html, json, xml, anything else undefined
pwa_LONG_TTL = 0 # 604800 is reasonable.

### list of files that overrides TTL_LONG/TTL_EXEMPT to be a NORM TTL.
pwa_TTL_NORM = '"sw.min.js", "sw_load.min.js"'

### TTL_LONG file extensions will be cached for the LONG_TTL duration.
pwa_TTL_LONG = '"jpg", "jpeg", "png", "gif", "webp", "avif", "ico", "svg", "xsl", "txt"'

### TTL_EXEMPT file extensions will be cached indefinitely unless sw_load version is incremented, which would invalidate any existing cache. (and a new cache would be started)
pwa_TTL_EXEMPT = '"js", "css", "otf", "eot", "ttf", "woff", "woff2", "mp4", "webm", "mp3", "ogg"'

### If set to true then the entire site is cached. (useful for making an entire site usable while offline)
pwa_cache_all = true

### List of Files for the PWA to initially Cache, used if pwa_cache_all = false
pwa_BASE_CACHE_FILES = "'/js/theme.min.js','/js/theme_light.min.js','/abridge.css','/js/abridge.min.js','/','/404.html','/offline/','/manifest.min.json'"

###############################################################################
### Favicons, comment out a line to disable loading some or all of these if needed.
###############################################################################

favicon_theme_color = "#333333"
favicon_ms_color = "#333333"
favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
favicon_mask_color = "#ff9900"
favicon_svg = "favicon.svg"            # favicon.svg
favicon180 = "apple-touch-icon.png"    # apple-touch-icon.png
favicon32 = "favicon-32x32.png"        # favicon-32x32.png
favicon16 = "favicon-16x16.png"        # favicon-16x16.png
