base_url = "https://hernangonzalez.github.io/rustar-resources"
title = "RustAR Resources"
description = "Please find here the content used in presentations during our meet-ups."
theme = "anemone"
default_language = "en"

[markdown]
highlight_code = true
render_emoji = true

[extra]
list_pages = true
display_author = false
toc = true
