name: Publish on GitHub Pages

on:
 workflow_dispatch:
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.1
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
